name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kupuyc/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          debug: no
          base: ""
          filename: images/metrics.svg
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: no
          plugin_languages_sections: most-used
